#!/usr/bin/env python3
"""
GLUT1 + SDG(PEG2) 복합체 생성
Phase 2 방식과 동일하게 적절한 위치에 리간드 배치
"""

def read_pdb_atoms(pdb_file, res_name=None):
    """PDB 파일에서 원자 정보 읽기"""
    atoms = []
    with open(pdb_file, 'r') as f:
        for line in f:
            if line.startswith(('ATOM', 'HETATM')):
                if res_name is None or res_name in line:
                    atoms.append(line)
    return atoms

def get_center_of_mass(atoms):
    """원자들의 질량 중심 계산"""
    coords = []
    for line in atoms:
        try:
            x = float(line[30:38])
            y = float(line[38:46])
            z = float(line[46:54])
            coords.append([x, y, z])
        except:
            continue
    
    if not coords:
        return None
    
    # 평균 계산
    x_avg = sum(c[0] for c in coords) / len(coords)
    y_avg = sum(c[1] for c in coords) / len(coords)
    z_avg = sum(c[2] for c in coords) / len(coords)
    
    return [x_avg, y_avg, z_avg]

def translate_atoms(atoms, translation):
    """원자 좌표 이동"""
    translated = []
    for line in atoms:
        if line.startswith(('ATOM', 'HETATM')):
            try:
                x = float(line[30:38])
                y = float(line[38:46])
                z = float(line[46:54])
                
                x += translation[0]
                y += translation[1]
                z += translation[2]
                
                new_line = line[:30] + f"{x:8.3f}{y:8.3f}{z:8.3f}" + line[54:]
                translated.append(new_line)
            except:
                translated.append(line)
        else:
            translated.append(line)
    
    return translated

def create_complex(glut1_pdb, ligand_pdb, output_pdb, target_position):
    """복합체 생성"""
    
    print(f"Reading GLUT1: {glut1_pdb}")
    glut1_atoms = read_pdb_atoms(glut1_pdb)
    print(f"  GLUT1 atoms: {len(glut1_atoms)}")
    
    print(f"\nReading Ligand: {ligand_pdb}")
    ligand_atoms = read_pdb_atoms(ligand_pdb)
    print(f"  Ligand atoms: {len(ligand_atoms)}")
    
    # 리간드 질량 중심 계산
    ligand_com = get_center_of_mass(ligand_atoms)
    print(f"\nLigand COM: {ligand_com}")
    print(f"Target position: {target_position}")
    
    # 이동 벡터 계산
    translation = [
        target_position[0] - ligand_com[0],
        target_position[1] - ligand_com[1],
        target_position[2] - ligand_com[2]
    ]
    print(f"Translation: {translation}")
    
    # 리간드 이동
    print("\nTranslating ligand...")
    translated_ligand = translate_atoms(ligand_atoms, translation)
    
    # 복합체 생성
    print(f"\nWriting complex: {output_pdb}")
    with open(output_pdb, 'w') as f:
        f.write("REMARK   GLUT1 + SDG(PEG2) complex\n")
        f.write("REMARK   Generated by create_glut1_sdg_peg2_complex.py\n")
        
        # GLUT1 원자들
        for line in glut1_atoms:
            f.write(line)
        
        # SDG 원자들
        for line in translated_ligand:
            f.write(line)
        
        f.write("END\n")
    
    print(f"\n✅ Complex created!")
    print(f"   Total atoms: {len(glut1_atoms) + len(translated_ligand)}")

# 실험군 (Glycosylated GLUT1)
print("="*70)
print("EXPERIMENTAL: Glycosylated GLUT1 + SDG(PEG2)")
print("="*70)

create_complex(
    glut1_pdb="/home/pjho3tr/Downloads/charmm-gui-6750265216membranebuilder/openmm/step5_input.pdb",
    ligand_pdb="/home/pjho3tr/Downloads/Ligand - 2PEG leg/ligandrm.pdb",
    output_pdb="/home/pjho3tr/projects/Drug/scripts/glut1_sdg_peg2_complex.pdb",
    target_position=[581.0, -17.8, 201.2]
)

# 대조군 (Non-glycosylated GLUT1)
print("\n" + "="*70)
print("CONTROL: Non-glycosylated GLUT1 + SDG(PEG2)")
print("="*70)

create_complex(
    glut1_pdb="/home/pjho3tr/Downloads/charmm-gui-6704990786대조군/openmm/step5_input.pdb",
    ligand_pdb="/home/pjho3tr/Downloads/Ligand - 2PEG leg/ligandrm.pdb",
    output_pdb="/home/pjho3tr/projects/Drug/scripts/glut1_sdg_peg2_complex_control.pdb",
    target_position=[581.0, -17.8, 201.2]
)

print("\n" + "="*70)
print("✅ Both complexes created successfully!")
print("="*70)
