#!/usr/bin/env python3
"""
Create Control Group GLUT1-Tripod complex (non-glycosylated)
Uses the same Phase 2 Tripod position
"""

import numpy as np
import sys
import os

def read_pdb_atoms(filename, select_type=None, select_resname=None):
    """Read PDB file and return atom information"""
    atoms = []
    
    with open(filename, 'r') as f:
        for line in f:
            if not (line.startswith('ATOM') or line.startswith('HETATM')):
                continue
            
            atom_name = line[12:16].strip()
            res_name = line[17:20].strip()
            chain_id = line[21].strip()
            res_num = line[22:26].strip()
            
            # Apply filters
            if select_type and atom_name != select_type:
                continue
            if select_resname and res_name != select_resname:
                continue
            
            x = float(line[30:38])
            y = float(line[38:46])
            z = float(line[46:54])
            
            atoms.append({
                'line': line.rstrip(),
                'atom': atom_name,
                'res': res_name,
                'chain': chain_id,
                'resnum': res_num,
                'coord': np.array([x, y, z])
            })
    
    return atoms

def kabsch_align(P, Q):
    """Kabsch algorithm for optimal rotation"""
    centroid_P = np.mean(P, axis=0)
    centroid_Q = np.mean(Q, axis=0)
    
    P_c = P - centroid_P
    Q_c = Q - centroid_Q
    
    H = Q_c.T @ P_c
    U, S, Vt = np.linalg.svd(H)
    R = Vt.T @ U.T
    
    if np.linalg.det(R) < 0:
        Vt[-1, :] *= -1
        R = Vt.T @ U.T
    
    t = centroid_P - R @ centroid_Q
    
    return R, t

def transform_atoms(atoms, R, t):
    """Apply rotation and translation to atoms"""
    transformed = []
    for atom in atoms:
        new_coord = R @ atom['coord'] + t
        new_atom = atom.copy()
        new_atom['coord'] = new_coord
        transformed.append(new_atom)
    return transformed

def write_pdb(atoms, filename, title="Structure"):
    """Write atoms to PDB file"""
    with open(filename, 'w') as f:
        f.write(f"REMARK   {title}\n")
        f.write(f"REMARK   Generated by create_control_complex.py\n")
        
        for i, atom in enumerate(atoms, 1):
            line = atom['line']
            coord = atom['coord']
            
            record = line[:6]
            atom_serial = f"{i:5d}"
            rest_before_coord = line[11:30]
            rest_after_coord = line[54:]
            
            new_line = (
                f"{record}{atom_serial} {rest_before_coord}"
                f"{coord[0]:8.3f}{coord[1]:8.3f}{coord[2]:8.3f}"
                f"{rest_after_coord}\n"
            )
            f.write(new_line)
        
        f.write("END\n")

def main():
    print("=" * 80)
    print("Control Group: Non-Glycosylated GLUT1-Tripod Complex")
    print("=" * 80)
    
    # File paths
    phase2_glut1_file = "phase2_glut1_coords.pdb"
    phase2_tripod_file = "phase2_tripod_coords.pdb"
    control_glut1_file = "/home/pjho3/다운로드/charmm-gui-6704990786대조군/step1_pdbreader.pdb"
    
    print("\n📁 Input files:")
    print(f"  Phase 2 GLUT1: {phase2_glut1_file}")
    print(f"  Phase 2 Tripod: {phase2_tripod_file}")
    print(f"  Control GLUT1 (non-glycosylated): {control_glut1_file}")
    
    # Step 1: Read Phase 2 structures
    print("\n📖 Step 1: Reading Phase 2 structures...")
    phase2_glut1_ca = read_pdb_atoms(phase2_glut1_file, select_type="CA")
    phase2_tripod = read_pdb_atoms(phase2_tripod_file)
    
    print(f"  Phase 2 GLUT1 CA atoms: {len(phase2_glut1_ca)}")
    print(f"  Phase 2 Tripod atoms: {len(phase2_tripod)}")
    
    # Step 2: Read control GLUT1 structure
    print("\n📖 Step 2: Reading control GLUT1 (non-glycosylated)...")
    control_glut1_ca = read_pdb_atoms(control_glut1_file, select_type="CA")
    control_glut1_all = read_pdb_atoms(control_glut1_file)
    
    print(f"  Control GLUT1 CA atoms: {len(control_glut1_ca)}")
    print(f"  Control GLUT1 total atoms: {len(control_glut1_all)}")
    
    # Step 3: Align GLUT1 structures
    print("\n🔄 Step 3: Aligning GLUT1 structures (Kabsch)...")
    
    P = np.array([atom['coord'] for atom in control_glut1_ca])  # Target (control)
    Q = np.array([atom['coord'] for atom in phase2_glut1_ca])  # Mobile (phase2)
    
    R, t = kabsch_align(P, Q)
    
    print(f"  Rotation matrix computed")
    print(f"  Translation vector: {t}")
    
    # Step 4: Transform Phase 2 Tripod
    print("\n🎯 Step 4: Transforming Tripod coordinates...")
    
    tripod_center_old = np.mean([atom['coord'] for atom in phase2_tripod], axis=0)
    print(f"  Tripod center (Phase 2): ({tripod_center_old[0]:.2f}, {tripod_center_old[1]:.2f}, {tripod_center_old[2]:.2f})")
    
    transformed_tripod = transform_atoms(phase2_tripod, R, t)
    
    tripod_center_new = np.mean([atom['coord'] for atom in transformed_tripod], axis=0)
    print(f"  Tripod center (aligned): ({tripod_center_new[0]:.2f}, {tripod_center_new[1]:.2f}, {tripod_center_new[2]:.2f})")
    
    # Step 5: Change residue name
    print("\n✏️  Step 5: Updating Tripod residue name (UNL → TRP)...")
    for atom in transformed_tripod:
        line = atom['line']
        atom['line'] = line[:17] + 'TRP' + line[20:]
    
    # Step 6: Combine
    print("\n🔗 Step 6: Creating control complex...")
    complex_atoms = control_glut1_all + transformed_tripod
    
    print(f"  Total atoms in complex: {len(complex_atoms)}")
    print(f"    GLUT1 (non-glycosylated): {len(control_glut1_all)}")
    print(f"    Tripod: {len(transformed_tripod)}")
    
    # Step 7: Write output
    print("\n💾 Step 7: Writing output files...")
    
    write_pdb(complex_atoms, "glut1_tripod_complex_control.pdb", 
              "GLUT1 (non-glycosylated) + Tripod complex - CONTROL GROUP")
    print("  ✅ glut1_tripod_complex_control.pdb")
    
    write_pdb(control_glut1_all, "glut1_control.pdb",
              "Non-glycosylated GLUT1 - CONTROL GROUP")
    print("  ✅ glut1_control.pdb")
    
    print("\n" + "=" * 80)
    print("✅ CONTROL GROUP COMPLEX CREATED!")
    print("=" * 80)
    
    print("\n📊 Summary:")
    print("  Experimental group: glut1_tripod_complex.pdb (WITH glycans)")
    print("  Control group:      glut1_tripod_complex_control.pdb (NO glycans)")
    
    print("\n📋 Both complexes ready for simulation!")
    print("=" * 80)

if __name__ == "__main__":
    main()
